- pyproject.toml
Bump opda's version to v0.3.0.
> Bump version to v0.3.0

- pyproject.toml
Bump opda's version to v0.4.0.
> Bump version to v0.4.0

- .github/workflows/build.yml
- CHANGELOG.rst
- README.rst
- docs/changelog.rst
- docs/index.rst
- pyproject.toml
Add a changelog:
* Add `CHANGELOG.rst` to the root of the repository.
* Include the changelog in the documentation when building it with Sphinx.
* Use a CI job to ensure that every pull request updates the changelog.
> Add a changelog

- CHANGELOG.rst
- docs/conf.py
Fix two issues related to the changelog:
* Add a missing line to the changelog's "Unreleased" section.
* Include `changelog_url` in `docs/conf.py`.
> Fix issues related to changelog

- .github/workflows/build.yml
- CHANGELOG.rst
- docs/conf.py
- docs/contributing/development.rst
- noxfile.py
- pyproject.toml
- src/opda/nonparametric.py
- tests/opda/test_nonparametric.py
Improve the development documentation and some tooling related to project maintenance.
> Improve maintenance docs and tools

- CHANGELOG.rst
- docs/conf.py
- docs/contributing/release.rst
- docs/index.rst
- noxfile.py
Add a process for making releases to PyPI.
> Add a release process

- CHANGELOG.rst
- pyproject.toml
Upgrade ``ruff``, ``pytest``, and ``lxml`` in the development dependencies.
> Upgrade development dependencies

- CHANGELOG.rst
- README.rst
- docs/conf.py
- docs/tutorial/setup.rst
- pyproject.toml
Bump opda's version to v0.5.0.
> Bump version to v0.5.0

- CHANGELOG.rst
Create a new "Unreleased" section in `CHANGELOG.rst`.
> Update changelog post-release

- CHANGELOG.rst
- docs/conf.py
- pyproject.toml
- src/opda/approximation.py
- src/opda/exceptions.py
- tests/opda/test_approximation.py
- tests/opda/test_exceptions.py
Add the `opda.approximation` module containing approximation-theoretic functions.
> Add approximation-theoretic functions

- CHANGELOG.rst
- tests/opda/test_parametric.py
Add two new tests to better vet `QuadraticDistribution`.
> Add more tests for QuadraticDistribution

- CHANGELOG.rst
- tests/opda/test_parametric.py
Add new tests and improve existing ones for `opda.parametric.QuadraticDistribution`.
> Add and improve tests

- CHANGELOG.rst
- README.rst
- data/deberta/README.md
- docs/tutorial/setup.rst
- nbs/optimal-design-analysis.ipynb
- pyproject.toml
Update all URLs in the repository to match the repository being renamed from `github.com/nalourie/opda` to `github.com/nicholaslourie/opda`.
> Update GitHub URLs

- CHANGELOG.rst
- src/experiments/analytic.py
- src/experiments/simulation.py
- src/experiments/visualization.py
- src/opda/approximation.py
- src/opda/nonparametric.py
- src/opda/parametric.py
- src/opda/utils.py
Improve the documentation and validation of constraints on the values for functions and methods' inputs and outputs.
> Improve documentation and validation of argument constraints

- CHANGELOG.rst
- src/experiments/analytic.py
- src/opda/nonparametric.py
- src/opda/parametric.py
- src/opda/utils.py
Document when values can be either scalars or arrays.
> Document scalar or array values

- CHANGELOG.rst
- docs/contributing/release.rst
- pyproject.toml
Bump opda's version to v0.6.0.
> Bump version to v0.6.0

- CHANGELOG.rst
Create a new "Unreleased" section in `CHANGELOG.rst`.
> Update changelog post-release v0.6.0

- CHANGELOG.rst
- pyproject.toml
Bump opda's version to v0.6.1.
> Bump version to v0.6.1

- CHANGELOG.rst
Create a new "Unreleased" section in `CHANGELOG.rst`.
> Update changelog post-release v0.6.1

- CHANGELOG.rst
- noxfile.py
- pyproject.toml
- tests/opda/test_nonparametric.py
Drop support for numpy 1.21 and remove related backwards compatibility code.
> Drop support for numpy 1.21

- CHANGELOG.rst
- data/resnet/LICENSE
- data/resnet/README.md
Add results for scaling hyperparameter tuning using random search for ResNet18 on ImageNet.
> Add ResNet hyperparameter scaling data

- CHANGELOG.rst
- noxfile.py
- pyproject.toml
- tests/opda/test_nonparametric.py
- tests/opda/test_parametric.py
- tests/opda/test_utils.py
Upgrade the packaging tools and supported versions of dependencies (`numpy` and `scipy`).
> Upgrade packaging tools and supported dependencies

- CHANGELOG.rst
- src/experiments/analytic.py
- src/experiments/simulation.py
- src/experiments/visualization.py
- src/opda/approximation.py
- src/opda/nonparametric.py
- src/opda/parametric.py
- src/opda/utils.py
Clean up the docstrings with various improvements.
> Clean up docstrings

- CHANGELOG.rst
- src/experiments/visualization.py
- src/opda/nonparametric.py
- src/opda/parametric.py
- tests/opda/test_parametric.py
Deliver miscellaneous improvements to the code.
> Miscellaneous code clean up

- CHANGELOG.rst
- docs/tutorial/setup.rst
- noxfile.py
- pyproject.toml
Update the supported dependencies.
> Add support for Python 3.13 and drop support for scipy 1.9

- CHANGELOG.rst
- pyproject.toml
Bump opda's version to v0.7.0.
> Bump version to v0.7.0

- CHANGELOG.rst
Create a new "Unreleased" section in `CHANGELOG.rst`.
> Update changelog post-release v0.7.0

- CHANGELOG.rst
- noxfile.py
Fix the support session in nox so that it more accurately determines the currently supported python versions.
> Fix support session in nox

- CHANGELOG.rst
- src/opda/parametric.py
- tests/opda/test_parametric.py
Make the optimization in `NoisyQuadraticDistribution.fit` more robust.
> Improve optimization in `NoisyQuadraticDistribution.fit`

- CHANGELOG.rst
- tests/opda/test_parametric.py
Fix flakiness in several tests to prevent spurious failures in continuous integration.
> Fix flaky tests

- CHANGELOG.rst
- data/deberta/README.md
- data/resnet/README.md
Add results from the residual experiment with ResNet18 on ImageNet.
> Add ResNet hyperparameter residual results

- CHANGELOG.rst
- data/resnet/README.md
Add results from the ablation experiment with ResNet18 on ImageNet.
> Add ResNet hyperparameter ablation results

- CHANGELOG.rst
- data/llama/LICENSE
- data/llama/README.md
Add results from the tuning experiment for Llama 33M on SlimPajama.
> Add Llama hyperparameter tuning results

- CHANGELOG.rst
- data/llama/README.md
Add results from the residual experiment for Llama 33M on SlimPajama.
> Add Llama hyperparameter residual results

- .github/workflows/build.yml
- CHANGELOG.rst
Parallelize the `testpackage` CI job over all dependencies.
> Parallelize `testpackage` over all dependencies

- CHANGELOG.rst
- docs/contributing/release.rst
- noxfile.py
Improve the release process for `opda`.
> Improve release process
